# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ProductListiOS' do
  pod 'YogaKit', '1.0.2'
  pod 'IGListKit', '2.1.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
  end
end
